# Setup a service account for sceptre integration tests
template_path: service-account.yaml
stack_name: sceptre-integration-test
parameters:
  ManagedPolicyArns:
    - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
    - arn:aws:iam::aws:policy/AmazonS3FullAccess
    - arn:aws:iam::aws:policy/AmazonSNSFullAccess
    - arn:aws:iam::aws:policy/AWSLambda_FullAccess
  PolicyDocument: >-
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "iam:ListPolicy",
            "iam:ListRoles",
            "iam:AttachRolePolicy",
            "iam:DeleteRolePolicy",
            "iam:DetachRolePolicy",
            "iam:GetRole",
            "iam:GetRolePolicy",
            "iam:ListAttachedRolePolicies",
            "iam:ListRolePolicies",
            "iam:PutRolePolicy",
            "iam:UpdateRole",
            "iam:UpdateRoleDescription",
            "iam:CreateRole",
            "iam:DeleteRole"
          ],
          "Resource": "*"
        }
      ]
    }
